// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAxwd3G5YClmhkm-mN1G9wcC39lw3vq1OQ',
    appId: '1:466335157884:web:b7a887a76d9604f16b03f9',
    messagingSenderId: '466335157884',
    projectId: 'iostrinkspielplatz',
    authDomain: 'iostrinkspielplatz.firebaseapp.com',
    databaseURL: 'https://iostrinkspielplatz-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'iostrinkspielplatz.appspot.com',
    measurementId: 'G-NS5GSBXRB0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD7KqcsEH3crzbc2puEviT9Zfzh6nfess4',
    appId: '1:466335157884:android:3d5ad4b9b58266386b03f9',
    messagingSenderId: '466335157884',
    projectId: 'iostrinkspielplatz',
    databaseURL: 'https://iostrinkspielplatz-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'iostrinkspielplatz.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBA-gB1aznO2ozMVcd_gITXtJW-Q6Ot0iw',
    appId: '1:466335157884:ios:1b27f8494928e6a96b03f9',
    messagingSenderId: '466335157884',
    projectId: 'iostrinkspielplatz',
    databaseURL: 'https://iostrinkspielplatz-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'iostrinkspielplatz.appspot.com',
    iosBundleId: 'com.charbelchougourou.trinkspielplatz',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBA-gB1aznO2ozMVcd_gITXtJW-Q6Ot0iw',
    appId: '1:466335157884:ios:8c5d3636cf5be8eb6b03f9',
    messagingSenderId: '466335157884',
    projectId: 'iostrinkspielplatz',
    databaseURL: 'https://iostrinkspielplatz-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'iostrinkspielplatz.appspot.com',
    iosBundleId: 'com.charbelchougourou.trinkspielplatz.RunnerTests',
  );
}
